clear; close all; clc;

%% 1. gap, gap_gap のリスト
gap_nm_values = 40:40:1000;
gap_gap_nm_values = 100:200:1000;

% ダブルチャネルのテキストファイルが置かれているフォルダ
input_folder_name = 'result/double_channel_step_40_gapgap_step_200_no_wall_jan26_parallel_grids_100_L04';
% シングルチャネルのテキストファイルが置かれているフォルダ
single_channel_folder_name = 'result/single_channel_step_40_jan23_parallel_grids_100_L04';

output_folder_name = 'result/plot_feb2';

% タイムスタンプ（保存ファイル名に付与すると便利）
timestamp_str = datestr(now, 'yyyy-mm-dd_HHMMSS');

%% 2. ダブルチャネル用データ格納用の配列 (gap vs gap_gap)
ngap    = length(gap_nm_values);
ngapgap = length(gap_gap_nm_values);

G1_abs_2D = nan(ngap, ngapgap);
G2_abs_2D = nan(ngap, ngapgap);
G_abs_sums_2D = nan(ngap, ngapgap);

%% 3. ダブルチャネルのテキストファイル読み込み
for iGap = 1:ngap
    gap_nm = gap_nm_values(iGap);
    
    for jGapGap = 1:ngapgap
        gap_gap_nm = gap_gap_nm_values(jGapGap);
        
        file_pattern = sprintf('final_acceleration_gradients_gap_%d_gapgap_%d_*.txt', gap_nm, gap_gap_nm);
        file_list = dir(fullfile(input_folder_name, file_pattern));
        
        if isempty(file_list)
            fprintf('Warning: %s が見つかりません。\n', file_pattern);
            continue;
        end
        
        target_file = fullfile(input_folder_name, file_list(1).name);
        file_text = fileread(target_file);
        
        tokens_G1 = regexp(file_text, 'G1_best \(abs\): ([0-9e\+\-\.]+)', 'tokens', 'once');
        tokens_G2 = regexp(file_text, 'G2_best \(abs\): ([0-9e\+\-\.]+)', 'tokens', 'once');
        
        if isempty(tokens_G1) || isempty(tokens_G2)
            fprintf('Warning: %s から必要な情報を取得できません。\n', target_file);
            continue;
        end
        
        val_G1_abs = str2double(tokens_G1{1});
        val_G2_abs = str2double(tokens_G2{1});
        
        G1_abs_2D(iGap, jGapGap) = val_G1_abs;
        G2_abs_2D(iGap, jGapGap) = val_G2_abs;
        G_abs_sums_2D(iGap, jGapGap) = val_G1_abs + val_G2_abs;
    end
end

%% 4. ダブルチャネルの派生量 (Power Equivalent Quantity)
REF_nm = 2000;  % 2000 nm で割るための定数

G1_peq_2D = (G1_abs_2D .* repmat(gap_nm_values(:), 1, ngapgap)) / REF_nm;
G2_peq_2D = (G2_abs_2D .* repmat(gap_nm_values(:), 1, ngapgap)) / REF_nm;
G_sum_peq_2D = G1_peq_2D + G2_peq_2D;

%% 5. シングルチャネルのデータ読み込み
sG_best_1D = nan(ngap,1);

for iGap = 1:ngap
    gnm = gap_nm_values(iGap);
    
    file_pattern = sprintf('final_acceleration_gradients_gap_%d_*_gap_%d.txt', gnm, gnm);
    file_list = dir(fullfile(single_channel_folder_name, file_pattern));
    
    if isempty(file_list)
        fprintf('Warning (SingleChannel): %s が見つかりません。\n', file_pattern);
        continue;
    end
    
    target_file = fullfile(single_channel_folder_name, file_list(1).name);
    file_text = fileread(target_file);
    
    tokens_G = regexp(file_text, 'G_best:\s*([0-9e\+\-\.]+)', 'tokens', 'once');
    if isempty(tokens_G)
        fprintf('Warning (SingleChannel): %s から G_best が取得できません。\n', target_file);
        continue;
    end
    
    sG_best_1D(iGap) = str2double(tokens_G{1});
end

% シングルチャネル用の Power Equivalent Quantity
sG_peq_1D = (sG_best_1D .* gap_nm_values(:)) / REF_nm;

%% 6. プロット用関数

% (A) 「for each gap_gap」(複数線プロット; ダブルチャネルのみ)
function plot_with_nan_handling(x_values, y_matrix, gap_gap_vals, x_label, y_label, title_str, save_path)
figure('Name', title_str);
hold on; grid on;
nLines = 0;
for j = 1:size(y_matrix, 2)
    y_values = y_matrix(:, j);
    valid_idx = ~isnan(y_values);
    if any(valid_idx)
        plot(x_values(valid_idx), y_values(valid_idx), '-o', ...
            'DisplayName', sprintf('gap\\_gap = %d nm', gap_gap_vals(j)));
        nLines = nLines + 1;
    end
end
xlabel(x_label, 'FontSize', 16);
ylabel(y_label, 'FontSize', 16);
title(title_str, 'FontSize', 16);

if nLines > 1
    legend('show', 'Location','best', 'FontSize', 16);
end
saveas(gcf, save_path);
end

% (B) gap_gap の中で最大値を抽出 (1本線を赤色でプロット)
function plot_max_over_gapgap(x_values, y_matrix, x_label, y_label, title_str, save_path)
figure('Name', title_str);
hold on; grid on;
max_vals = max(y_matrix, [], 2, 'omitnan');
co = get(groot, 'DefaultAxesColorOrder');
plot(x_values, max_vals, '-o', 'Color', co(2, :));
xlabel(x_label, 'FontSize', 16);
ylabel(y_label, 'FontSize', 16);
title(title_str, 'FontSize', 16);
saveas(gcf, save_path);
end

% (C) gap_gap で最大値 + シングル (2本線; channel 1 と single)
function plot_max_over_gapgap_with_single(x_values, y_matrix, single_values, x_label, y_label, title_str, save_path, legend_dc, legend_sg)
figure('Name', title_str);
hold on; grid on;
co = get(groot, 'DefaultAxesColorOrder');
max_vals = max(y_matrix, [], 2, 'omitnan');
plot(x_values, single_values, '-o', 'Color', co(1, :), 'DisplayName', legend_sg);
plot(x_values, max_vals, '-o', 'Color', co(2, :), 'DisplayName', legend_dc);
xlabel(x_label, 'FontSize', 16);
ylabel(y_label, 'FontSize', 16);
title(title_str, 'FontSize', 16);
legend('show', 'Location','best', 'FontSize', 16);
saveas(gcf, save_path);
end

% (D) シングルチャネルのみのグラフ
function plot_single_only(x_values, single_values, x_label, y_label, title_str, save_path)
figure('Name', title_str);
hold on; grid on;
plot(x_values, single_values, '-o');
xlabel(x_label, 'FontSize', 16);
ylabel(y_label, 'FontSize', 16);
title(title_str, 'FontSize', 16);
saveas(gcf, save_path);
end

% (E) channel1, channel2, single の加速勾配をまとめて描画する関数
%     ※ 各 gap における「best gap\_gap」（最大値）をそれぞれ算出してプロット
function plot_max_over_gapgap_with_single_and_ch2(x_values, y_matrix_ch1, y_matrix_ch2, single_values, x_label, y_label, title_str, save_path, legend_ch1, legend_ch2, legend_sg)
figure('Name', title_str);
hold on; grid on;
co = get(groot, 'DefaultAxesColorOrder');

% 各チャネルの最大値（各 gap に対して）
max_vals_ch1 = max(y_matrix_ch1, [], 2, 'omitnan');
max_vals_ch2 = max(y_matrix_ch2, [], 2, 'omitnan');

% プロット： single (青: co(1,:))、channel1 (赤: co(2,:))、channel2 (緑: co(3,:))
plot(x_values, single_values, '-o', 'Color', co(1,:), 'DisplayName', legend_sg);
plot(x_values, max_vals_ch1, '-o', 'Color', co(2,:), 'DisplayName', legend_ch1);
plot(x_values, max_vals_ch2, '-o', 'Color', co(3,:), 'DisplayName', legend_ch2);

xlabel(x_label, 'FontSize', 16);
ylabel(y_label, 'FontSize', 16);
title(title_str, 'FontSize', 16);
legend('show', 'Location','best', 'FontSize', 16);
saveas(gcf, save_path);
end

%% 7. グラフ出力

% (A) for each gap_gap (ダブルチャネルのみ)
plot_with_nan_handling( ...
    gap_nm_values, G1_peq_2D, gap_gap_nm_values, ...
    'gap (nm)', 'Power Equivalent Quantity (channel 1)', ...
    'Power Equivalent Quantity (channel 1) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['peq_g1_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
    );
plot_with_nan_handling( ...
    gap_nm_values, G2_peq_2D, gap_gap_nm_values, ...
    'gap (nm)', 'Power Equivalent Quantity (channel 2)', ...
    'Power Equivalent Quantity (channel 2) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['peq_g2_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
    );
plot_with_nan_handling( ...
    gap_nm_values, G1_abs_2D, gap_gap_nm_values, ...
    'gap (nm)', 'Acceleration Gradient (channel 1)', ...
    'Acceleration Gradient (channel 1) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['grad_g1_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
    );
plot_with_nan_handling( ...
    gap_nm_values, G2_abs_2D, gap_gap_nm_values, ...
    'gap (nm)', 'Acceleration Gradient (channel 2)', ...
    'Acceleration Gradient (channel 2) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['grad_g2_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
    );
plot_with_nan_handling( ...
    gap_nm_values, G_abs_sums_2D, gap_gap_nm_values, ...
    'gap (nm)', 'Acceleration Gradient (Total)', ...
    'Acceleration Gradient (Total) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['grad_gsum_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
    );
plot_with_nan_handling( ...
    gap_nm_values, G_sum_peq_2D, gap_gap_nm_values, ...
    'gap (nm)', 'Power Equivalent Quantity (Total)', ...
    'Power Equivalent Quantity (Total) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['peq_gsum_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
    );

% (B) gap_gap で最大値 (ダブルチャネルのみ, 1本線)
plot_max_over_gapgap( ...
    gap_nm_values, G1_peq_2D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (channel 1) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_peq_g1_vs_gap_', timestamp_str, '.png']) ...
    );
plot_max_over_gapgap( ...
    gap_nm_values, G2_peq_2D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (channel 2) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_peq_g2_vs_gap_', timestamp_str, '.png']) ...
    );
plot_max_over_gapgap( ...
    gap_nm_values, G1_abs_2D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (channel 1) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_g1_vs_gap_', timestamp_str, '.png']) ...
    );
plot_max_over_gapgap( ...
    gap_nm_values, G2_abs_2D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (channel 2) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_g2_vs_gap_', timestamp_str, '.png']) ...
    );
plot_max_over_gapgap( ...
    gap_nm_values, G_abs_sums_2D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (Total) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_gsum_vs_gap_', timestamp_str, '.png']) ...
    );
plot_max_over_gapgap( ...
    gap_nm_values, G_sum_peq_2D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (Total) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_peq_gsum_vs_gap_', timestamp_str, '.png']) ...
    );

% (C) gap_gap で最大値 + シングル (2本線: channel 1 と single)
plot_max_over_gapgap_with_single( ...
    gap_nm_values, G1_peq_2D, sG_peq_1D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (channel 1 & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_peq_g1_vs_gap_with_single_', timestamp_str, '.png']), ...
    'Double channel (best gap\_gap)', 'Single channel' ...
    );
plot_max_over_gapgap_with_single( ...
    gap_nm_values, G2_peq_2D, sG_peq_1D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (channel 2 & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_peq_g2_vs_gap_with_single_', timestamp_str, '.png']), ...
    'Double channel (best gap\_gap)', 'Single channel' ...
    );
plot_max_over_gapgap_with_single( ...
    gap_nm_values, G1_abs_2D, sG_best_1D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (channel 1 & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_g1_vs_gap_with_single_', timestamp_str, '.png']), ...
    'Double channel (best gap\_gap)', 'Single channel' ...
    );
plot_max_over_gapgap_with_single( ...
    gap_nm_values, G2_abs_2D, sG_best_1D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (channel 2 & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_g2_vs_gap_with_single_', timestamp_str, '.png']), ...
    'Double channel (best gap\_gap)', 'Single channel' ...
    );
plot_max_over_gapgap_with_single( ...
    gap_nm_values, G_abs_sums_2D, sG_best_1D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (total & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_gsum_vs_gap_with_single_', timestamp_str, '.png']), ...
    'Double channel (best gap\_gap)', 'Single channel' ...
    );
plot_max_over_gapgap_with_single( ...
    gap_nm_values, G_sum_peq_2D, sG_peq_1D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (total & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_peq_gsum_vs_gap_with_single_', timestamp_str, '.png']), ...
    'Double channel (best gap\_gap)', 'Single channel' ...
    );

% (E) channel1, channel2, single をまとめたグラフ (3本線)
plot_max_over_gapgap_with_single_and_ch2( ...
    gap_nm_values, G1_abs_2D, G2_abs_2D, sG_best_1D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (channel 1, channel 2 & single) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['max_grad_ch1_ch2_single_vs_gap_', timestamp_str, '.png']), ...
    'Double channel (ch1, best gap\_gap)', 'Double channel (ch2, best gap\_gap)', 'Single channel' ...
    );

% (D) シングルチャネルのみのグラフ
plot_single_only( ...
    gap_nm_values, sG_best_1D, ...
    'gap (nm)', 'Acceleration Gradient', ...
    'Acceleration Gradient (single) vs gap', ...
    fullfile(output_folder_name, ['single_acc_grad_vs_gap_', timestamp_str, '.png']) ...
    );
plot_single_only( ...
    gap_nm_values, sG_peq_1D, ...
    'gap (nm)', 'Power Equivalent Quantity', ...
    'Power Equivalent Quantity (single) vs gap', ...
    fullfile(output_folder_name, ['single_peq_vs_gap_', timestamp_str, '.png']) ...
    );

fprintf('=== Done. グラフを出力しました ===\n');
