clear; close all; clc;

%% 1. gap, gap_gap のリスト
gap_nm_values = 40:40:1000;
gap_gap_nm_values = 100:200:1000;

% テキストファイルが置かれているフォルダ
input_folder_name = 'result/double_channel_step_40_gapgap_step_200_no_wall_jan26_parallel_grids_100_L04';
output_folder_name = 'result/no_wall_jan26_new';

% タイムスタンプ（保存ファイル名に付与すると便利）
timestamp_str = datestr(now, 'yyyy-mm-dd_HHMMSS');

%% 2. データ格納用の配列 (gap vs gap_gap)
ngap    = length(gap_nm_values);
ngapgap = length(gap_gap_nm_values);

% abs(g1), abs(g2), abs(g1)+abs(g2) を格納 (NaN初期化)
G1_abs_2D = nan(ngap, ngapgap);
G2_abs_2D = nan(ngap, ngapgap);
G_abs_sums_2D = nan(ngap, ngapgap);

%% 3. テキストファイルを読み込んで、各種値を取得
for iGap = 1:ngap
    gap_nm = gap_nm_values(iGap);
    
    for jGapGap = 1:ngapgap
        gap_gap_nm = gap_gap_nm_values(jGapGap);
        
        % ファイル名のパターン
        file_pattern = sprintf('final_acceleration_gradients_gap_%d_gapgap_%d_*.txt', ...
            gap_nm, gap_gap_nm);
        file_list = dir(fullfile(input_folder_name, file_pattern));
        
        if isempty(file_list)
            % 対応するファイルが存在しない場合はスキップ (NaNのまま)
            fprintf('Warning: %s が見つかりません。\n', file_pattern);
            continue;
        end
        
        % ファイル読み込み
        target_file = fullfile(input_folder_name, file_list(1).name);
        file_text = fileread(target_file);
        
        % abs(g1) と abs(g2) を抽出
        tokens_G1 = regexp(file_text, 'G1_best \(abs\): ([0-9e\+\-\.]+)', 'tokens', 'once');
        tokens_G2 = regexp(file_text, 'G2_best \(abs\): ([0-9e\+\-\.]+)', 'tokens', 'once');
        
        if isempty(tokens_G1) || isempty(tokens_G2)
            fprintf('Warning: %s から必要な情報を取得できません。\n', target_file);
            continue;
        end
        
        val_G1_abs = str2double(tokens_G1{1});
        val_G2_abs = str2double(tokens_G2{1});
        
        G1_abs_2D(iGap, jGapGap) = val_G1_abs;
        G2_abs_2D(iGap, jGapGap) = val_G2_abs;
        G_abs_sums_2D(iGap, jGapGap) = val_G1_abs + val_G2_abs;
    end
end

%% 4. 派生量の計算
% abs(g1)*gap, abs(g2)*gap, (abs(g1)+abs(g2))*gap
G1_abs_times_gap_2D = G1_abs_2D .* repmat(gap_nm_values(:), 1, ngapgap);
G2_abs_times_gap_2D = G2_abs_2D .* repmat(gap_nm_values(:), 1, ngapgap);
G_abs_sums_times_gap_2D = G_abs_sums_2D .* repmat(gap_nm_values(:), 1, ngapgap);

%% 5. プロット用関数
% 欠損 (NaN) データがあっても線をつなぐようにする
function plot_with_nan_handling(x_values, y_matrix, gap_gap_vals, ...
    xlabel_text, ylabel_text, title_text, save_path)

    figure('Name', title_text);
    hold on; grid on;
    for j = 1:size(y_matrix, 2)
        y_values = y_matrix(:, j);
        valid_idx = ~isnan(y_values);
        if any(valid_idx)
            plot(x_values(valid_idx), y_values(valid_idx), '-o', ...
                'DisplayName', sprintf('gap\\_gap = %d nm', gap_gap_vals(j)));
        end
    end
    xlabel(xlabel_text);
    ylabel(ylabel_text);
    title(title_text);
    legend('show', 'Location','best');
    saveas(gcf, save_path);
end

% gap_gap の中で最大値を抽出してプロット
function plot_max_over_gapgap(x_values, y_matrix, ...
    xlabel_text, ylabel_text, title_text, save_path)

    figure('Name', title_text);
    hold on; grid on;
    % 行方向(gap方向)に対して列方向(gap_gap方向)の最大値
    max_vals = max(y_matrix, [], 2, 'omitnan');
    plot(x_values, max_vals, '-o');
    
    xlabel(xlabel_text);
    ylabel(ylabel_text);
    title(title_text);
    saveas(gcf, save_path);
end

%% 6. グラフ出力

% ========== 6-1. abs(g1)*gap vs gap (for each gap_gap) ==========
plot_with_nan_handling( ...
    gap_nm_values, ...
    G1_abs_times_gap_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1) * gap', ...
    'abs(g1) * gap vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['plot_abs_g1_times_gap_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% (max over gap_gap)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G1_abs_times_gap_2D, ...
    'gap (nm)', ...
    'abs(g1) * gap', ...
    'abs(g1) * gap vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_times_gap_vs_gap_', timestamp_str, '.png']) ...
);


% ========== 6-2. abs(g2)*gap vs gap (for each gap_gap) ==========
plot_with_nan_handling( ...
    gap_nm_values, ...
    G2_abs_times_gap_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g2) * gap', ...
    'abs(g2) * gap vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['plot_abs_g2_times_gap_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% (max over gap_gap)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G2_abs_times_gap_2D, ...
    'gap (nm)', ...
    'abs(g2) * gap', ...
    'abs(g2) * gap vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['plot_max_abs_g2_times_gap_vs_gap_', timestamp_str, '.png']) ...
);


% ========== 6-3. abs(g1) vs gap (for each gap_gap) ========== (追加)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G1_abs_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1)', ...
    'abs(g1) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['plot_abs_g1_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% (max over gap_gap)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G1_abs_2D, ...
    'gap (nm)', ...
    'abs(g1)', ...
    'abs(g1) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_vs_gap_', timestamp_str, '.png']) ...
);


% ========== 6-4. abs(g2) vs gap (for each gap_gap) ========== (追加)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G2_abs_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g2)', ...
    'abs(g2) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['plot_abs_g2_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% (max over gap_gap)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G2_abs_2D, ...
    'gap (nm)', ...
    'abs(g2)', ...
    'abs(g2) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['plot_max_abs_g2_vs_gap_', timestamp_str, '.png']) ...
);


% ========== 6-5. abs(g1)+abs(g2) vs gap (for each gap_gap) ========== (追加)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G_abs_sums_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1) + abs(g2)', ...
    'abs(g1) + abs(g2) vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['plot_abs_g1_plus_abs_g2_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% (max over gap_gap)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G_abs_sums_2D, ...
    'gap (nm)', ...
    'abs(g1) + abs(g2)', ...
    'abs(g1) + abs(g2) vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_plus_abs_g2_vs_gap_', timestamp_str, '.png']) ...
);


% ========== 6-6. (abs(g1)+abs(g2))*gap vs gap (for each gap_gap) ==========
plot_with_nan_handling( ...
    gap_nm_values, ...
    G_abs_sums_times_gap_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1) * gap + abs(g2) * gap', ...
    'abs(g1) * gap + abs(g2) * gap vs gap for each gap\_gap', ...
    fullfile(output_folder_name, ['plot_abs_sum_times_gap_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% (max over gap_gap)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G_abs_sums_times_gap_2D, ...
    'gap (nm)', ...
    'abs(g1) * gap + abs(g2) * gap', ...
    'abs(g1) * gap + abs(g2) * gap vs gap (best gap\_gap)', ...
    fullfile(output_folder_name, ['plot_max_abs_sum_times_gap_vs_gap_', timestamp_str, '.png']) ...
);

fprintf('=== Done. 合計12種類(各2パターン)のグラフを出力しました ===\n');
