clear; close all; clc;

%% 1. gap, gap_gap のリスト
gap_nm_values = 40:40:1000;
gap_gap_nm_values = 100:200:1000;

% ダブルチャネルのテキストファイルが置かれているフォルダ
input_folder_name = 'result/double_channel_step_40_gapgap_step_200_no_wall_jan26_parallel_grids_100_L04';
% シングルチャネルのテキストファイルが置かれているフォルダ
single_channel_folder_name = 'result/single_channel_step_40_jan23_parallel_grids_100_L04';

output_folder_name = 'result/no_wall_single_legend_jan27';

% タイムスタンプ（保存ファイル名に付与すると便利）
timestamp_str = datestr(now, 'yyyy-mm-dd_HHMMSS');

%% 2. データ格納用の配列 (gap vs gap_gap) -- ダブルチャネル
ngap    = length(gap_nm_values);
ngapgap = length(gap_gap_nm_values);

% abs(g1), abs(g2), abs(g1)+abs(g2) を格納 (NaN初期化; ダブルチャネル用)
G1_abs_2D = nan(ngap, ngapgap);
G2_abs_2D = nan(ngap, ngapgap);
G_abs_sums_2D = nan(ngap, ngapgap);

%% 3. ダブルチャネルのテキストファイル読み込み
for iGap = 1:ngap
    gap_nm = gap_nm_values(iGap);
    
    for jGapGap = 1:ngapgap
        gap_gap_nm = gap_gap_nm_values(jGapGap);
        
        % ファイル名のパターン
        file_pattern = sprintf('final_acceleration_gradients_gap_%d_gapgap_%d_*.txt', ...
            gap_nm, gap_gap_nm);
        file_list = dir(fullfile(input_folder_name, file_pattern));
        
        if isempty(file_list)
            fprintf('Warning: %s が見つかりません。\n', file_pattern);
            continue;
        end
        
        target_file = fullfile(input_folder_name, file_list(1).name);
        file_text = fileread(target_file);
        
        % abs(g1) と abs(g2) を抽出
        tokens_G1 = regexp(file_text, 'G1_best \(abs\): ([0-9e\+\-\.]+)', 'tokens', 'once');
        tokens_G2 = regexp(file_text, 'G2_best \(abs\): ([0-9e\+\-\.]+)', 'tokens', 'once');
        
        if isempty(tokens_G1) || isempty(tokens_G2)
            fprintf('Warning: %s から必要な情報を取得できません。\n', target_file);
            continue;
        end
        
        val_G1_abs = str2double(tokens_G1{1});
        val_G2_abs = str2double(tokens_G2{1});
        
        G1_abs_2D(iGap, jGapGap) = val_G1_abs;
        G2_abs_2D(iGap, jGapGap) = val_G2_abs;
        G_abs_sums_2D(iGap, jGapGap) = val_G1_abs + val_G2_abs;
    end
end

%% 4. ダブルチャネルの派生量の計算
% abs(g1)*gap, abs(g2)*gap, abs(g1)*gap + abs(g2)*gap
G1_abs_times_gap_2D = G1_abs_2D .* repmat(gap_nm_values(:), 1, ngapgap);
G2_abs_times_gap_2D = G2_abs_2D .* repmat(gap_nm_values(:), 1, ngapgap);
G_abs_sums_times_gap_2D = G1_abs_times_gap_2D + G2_abs_times_gap_2D;  % 変更: (abs(g1)+abs(g2))*gap → abs(g1)*gap + abs(g2)*gap

%% 5. シングルチャネルのデータ読み込み (G_best)
% テキスト例:
%   G_best: 0.067343
%   g_best: 0.063195 + 0.023270i
%   E_max: 3.757492
%   L: 0.400000

sG_best_1D = nan(ngap,1);  % シングルチャネルの G_best

for iGap = 1:ngap
    gnm = gap_nm_values(iGap);
    
    file_pattern = sprintf('final_acceleration_gradients_gap_%d_*_gap_%d.txt', gnm, gnm);
    file_list = dir(fullfile(single_channel_folder_name, file_pattern));
    
    if isempty(file_list)
        fprintf('Warning (SingleChannel): %s が見つかりません。\n', file_pattern);
        continue;
    end
    
    target_file = fullfile(single_channel_folder_name, file_list(1).name);
    file_text = fileread(target_file);
    
    % "G_best:" を抽出
    tokens_G = regexp(file_text, 'G_best:\s*([0-9e\+\-\.]+)', 'tokens', 'once');
    if isempty(tokens_G)
        fprintf('Warning (SingleChannel): %s から G_best が取得できません。\n', target_file);
        continue;
    end
    
    sG_best_1D(iGap) = str2double(tokens_G{1});
end

% シングルチャネルの派生量: G_best * gap
sG_best_times_gap_1D = sG_best_1D .* gap_nm_values(:);

%% 6. プロット用関数

% (A) 「for each gap_gap」ダブルチャネルのみ
%     欠損 (NaN) データがあっても線をつなぐようにし、複数線なら凡例を表示
function plot_with_nan_handling(x_values, y_matrix, gap_gap_vals, ...
    xlabel_text, ylabel_text, title_text, save_path)
    figure('Name', title_text);
    hold on; grid on;
    nLines = 0;
    for j = 1:size(y_matrix, 2)
        y_values = y_matrix(:, j);
        valid_idx = ~isnan(y_values);
        if any(valid_idx)
            plot(x_values(valid_idx), y_values(valid_idx), '-o', ...
                'DisplayName', sprintf('gap_gap = %d nm', gap_gap_vals(j)));
            nLines = nLines + 1;
        end
    end
    xlabel(xlabel_text);
    ylabel(ylabel_text);
    title(title_text);

    % 複数線(2本以上)なら凡例表示、1本以下なら非表示でもOK
    if nLines > 1
        legend('show', 'Location','best');
    end
    
    saveas(gcf, save_path);
end

% (B) ダブルチャネルのみ: gap_gap の中で最大値を抽出してプロット（1本なので凡例オフ）
function plot_max_over_gapgap(x_values, y_matrix, xlabel_text, ylabel_text, title_text, save_path)
    figure('Name', title_text);
    hold on; grid on;
    max_vals = max(y_matrix, [], 2, 'omitnan');
    
    % ダブルチャネル(最大) (1本)
    plot(x_values, max_vals, '-o');

    xlabel(xlabel_text);
    ylabel(ylabel_text);
    title(title_text);

    % 凡例表示しない（1種類の線のみ）
    % legend('off'); % デフォルトで表示されないので特に書かなくてもOK
    
    saveas(gcf, save_path);
end

% (C) ダブルチャネル (best gap_gap) + シングルチャネル 重ね描画（2本なので凡例オン）
function plot_max_over_gapgap_with_single(x_values, y_matrix, single_values, ...
    xlabel_text, ylabel_text, title_text, save_path)
    figure('Name', title_text);
    hold on; grid on;
    
    % ダブルチャネルの最大値
    max_vals = max(y_matrix, [], 2, 'omitnan');
    
    % ダブルチャネル(最大)
    plot(x_values, max_vals, '-o', 'DisplayName', 'Double channel (best gap_gap)');
    
    % シングルチャネル
    plot(x_values, single_values, '-o', 'DisplayName', 'Single channel');
    
    xlabel(xlabel_text);
    ylabel(ylabel_text);
    title(title_text);
    
    legend('show', 'Location','best');
    saveas(gcf, save_path);
end

%% 7. グラフ出力 (合計18個)

%--------------------------------------------------
% (A) "for each gap_gap" ダブルチャネルのみ (6種類)
%--------------------------------------------------

% 1) abs(g1)*gap
plot_with_nan_handling( ...
    gap_nm_values, ...
    G1_abs_times_gap_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1)*gap', ...
    'abs(g1)*gap vs gap for each gap_gap', ...
    fullfile(output_folder_name, ['plot_abs_g1_times_gap_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% 2) abs(g2)*gap
plot_with_nan_handling( ...
    gap_nm_values, ...
    G2_abs_times_gap_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g2)*gap', ...
    'abs(g2)*gap vs gap for each gap_gap', ...
    fullfile(output_folder_name, ['plot_abs_g2_times_gap_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% 3) abs(g1)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G1_abs_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1)', ...
    'abs(g1) vs gap for each gap_gap', ...
    fullfile(output_folder_name, ['plot_abs_g1_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% 4) abs(g2)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G2_abs_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g2)', ...
    'abs(g2) vs gap for each gap_gap', ...
    fullfile(output_folder_name, ['plot_abs_g2_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% 5) abs(g1) + abs(g2)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G_abs_sums_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1) + abs(g2)', ...
    'abs(g1) + abs(g2) vs gap for each gap_gap', ...
    fullfile(output_folder_name, ['plot_abs_g1_plus_abs_g2_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);

% 6) abs(g1)*gap + abs(g2)*gap  (← 表記を変更)
plot_with_nan_handling( ...
    gap_nm_values, ...
    G_abs_sums_times_gap_2D, ...
    gap_gap_nm_values, ...
    'gap (nm)', ...
    'abs(g1)*gap + abs(g2)*gap', ... 
    'abs(g1)*gap + abs(g2)*gap vs gap for each gap_gap', ...
    fullfile(output_folder_name, ['plot_abs_sum_times_gap_vs_gap_for_each_gapgap_', timestamp_str, '.png']) ...
);


%--------------------------------------------------
% (B) "best gap_gap" ダブルチャネルのみ (6種類) - (1本)
%   ⇒ 凡例は表示しない
%--------------------------------------------------

% 1) abs(g1)*gap
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G1_abs_times_gap_2D, ...
    'gap (nm)', ...
    'abs(g1)*gap', ...
    'abs(g1)*gap vs gap (best gap_gap) - double only', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_times_gap_vs_gap_', timestamp_str, '.png']) ...
);

% 2) abs(g2)*gap
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G2_abs_times_gap_2D, ...
    'gap (nm)', ...
    'abs(g2)*gap', ...
    'abs(g2)*gap vs gap (best gap_gap) - double only', ...
    fullfile(output_folder_name, ['plot_max_abs_g2_times_gap_vs_gap_', timestamp_str, '.png']) ...
);

% 3) abs(g1)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G1_abs_2D, ...
    'gap (nm)', ...
    'abs(g1)', ...
    'abs(g1) vs gap (best gap_gap) - double only', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_vs_gap_', timestamp_str, '.png']) ...
);

% 4) abs(g2)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G2_abs_2D, ...
    'gap (nm)', ...
    'abs(g2)', ...
    'abs(g2) vs gap (best gap_gap) - double only', ...
    fullfile(output_folder_name, ['plot_max_abs_g2_vs_gap_', timestamp_str, '.png']) ...
);

% 5) abs(g1) + abs(g2)
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G_abs_sums_2D, ...
    'gap (nm)', ...
    'abs(g1) + abs(g2)', ...
    'abs(g1) + abs(g2) vs gap (best gap_gap) - double only', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_plus_abs_g2_vs_gap_', timestamp_str, '.png']) ...
);

% 6) abs(g1)*gap + abs(g2)*gap
plot_max_over_gapgap( ...
    gap_nm_values, ...
    G_abs_sums_times_gap_2D, ...
    'gap (nm)', ...
    'abs(g1)*gap + abs(g2)*gap', ...
    'abs(g1)*gap + abs(g2)*gap vs gap (best gap_gap) - double only', ...
    fullfile(output_folder_name, ['plot_max_abs_sum_times_gap_vs_gap_', timestamp_str, '.png']) ...
);


%--------------------------------------------------
% (C) "best gap_gap" + シングルチャネル (6種類) - (2本線)
%   ⇒ 凡例を表示する
%--------------------------------------------------

% 1) abs(g1)*gap  <-->  G_best * gap
plot_max_over_gapgap_with_single( ...
    gap_nm_values, ...
    G1_abs_times_gap_2D, ...
    sG_best_times_gap_1D, ...  % シングル = G_best * gap
    'gap (nm)', ...
    'abs(g1)*gap', ...
    'abs(g1)*gap vs gap (best gap_gap) + single channel', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_times_gap_vs_gap_with_single_', timestamp_str, '.png']) ...
);

% 2) abs(g2)*gap  <-->  G_best * gap
plot_max_over_gapgap_with_single( ...
    gap_nm_values, ...
    G2_abs_times_gap_2D, ...
    sG_best_times_gap_1D, ...  
    'gap (nm)', ...
    'abs(g2)*gap', ...
    'abs(g2)*gap vs gap (best gap_gap) + single channel', ...
    fullfile(output_folder_name, ['plot_max_abs_g2_times_gap_vs_gap_with_single_', timestamp_str, '.png']) ...
);

% 3) abs(g1)  <-->  G_best
plot_max_over_gapgap_with_single( ...
    gap_nm_values, ...
    G1_abs_2D, ...
    sG_best_1D, ... 
    'gap (nm)', ...
    'abs(g1)', ...
    'abs(g1) vs gap (best gap_gap) + single channel', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_vs_gap_with_single_', timestamp_str, '.png']) ...
);

% 4) abs(g2)  <-->  G_best
plot_max_over_gapgap_with_single( ...
    gap_nm_values, ...
    G2_abs_2D, ...
    sG_best_1D, ...
    'gap (nm)', ...
    'abs(g2)', ...
    'abs(g2) vs gap (best gap_gap) + single channel', ...
    fullfile(output_folder_name, ['plot_max_abs_g2_vs_gap_with_single_', timestamp_str, '.png']) ...
);

% 5) abs(g1) + abs(g2)  <-->  G_best
plot_max_over_gapgap_with_single( ...
    gap_nm_values, ...
    G_abs_sums_2D, ...
    sG_best_1D, ...
    'gap (nm)', ...
    'abs(g1) + abs(g2)', ...
    'abs(g1) + abs(g2) vs gap (best gap_gap) + single channel', ...
    fullfile(output_folder_name, ['plot_max_abs_g1_plus_abs_g2_vs_gap_with_single_', timestamp_str, '.png']) ...
);

% 6) abs(g1)*gap + abs(g2)*gap  <-->  G_best * gap
plot_max_over_gapgap_with_single( ...
    gap_nm_values, ...
    G_abs_sums_times_gap_2D, ...
    sG_best_times_gap_1D, ...
    'gap (nm)', ...
    'abs(g1)*gap + abs(g2)*gap', ...
    'abs(g1)*gap + abs(g2)*gap vs gap (best gap_gap) + single channel', ...
    fullfile(output_folder_name, ['plot_max_abs_sum_times_gap_vs_gap_with_single_', timestamp_str, '.png']) ...
);

fprintf('=== Done. 合計18枚のグラフを出力しました ===\n');
